### ISSUE TITLE
StartInfo's Attribution   

### ISSUE THREAD

**Issue by infinitylight** [dotnet/dotnet-api-docs.zh-cn#22]
[在此处输入反馈]

Maybe the "public System.Diagnostics.ProcessStartInfo StartInfo { get; set; }" should be 
"public System.Diagnostics.Process.StartInfo{ get; set; }".
If the "public System.Diagnostics.ProcessStartInfo StartInfo { get; set; }" is right is meaning the 
StartInfo belongs both Process Class and ProcessStartInfo Class!
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 61b333a8-bdf9-4222-41d1-e9044cc92b66
* Version Independent ID: 9e3d7bfa-b873-f155-6a54-8e9877a8dc2a
* Content: [Process.StartInfo Property (System.Diagnostics)](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process.startinfo?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
There is no error. It's auto generated from source code.

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2210](https://github.com/dotnet/dotnet-api-docs/issues/2210) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @infinitylight 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2210

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
