### ISSUE TITLE
SslStream is available in UWP 10.0.16299 but not addressed here

### ISSUE THREAD

**Issue by taoyouh** [dotnet/dotnet-api-docs.zh-cn#25]
Class SslStream and method SslStream.ShutdownAsync is available in UWP 10.0.16299 or higher. But it is not mentioned in the document.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 29aea839-74d6-6dfe-c54d-e1714a3b3367
* Version Independent ID: 9d8d412d-571e-c0df-439d-6adfbc334664
* Content: [SslStream.ShutdownAsync Method (System.Net.Security)](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.security.sslstream.shutdownasync?view=netframework-4.7.2&viewFallbackFrom=dotnet-plat-ext-2.1#feedback)
* Content Source: [xml/System.Net.Security/SslStream.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Net.Security/SslStream.xml)
* Product: **dotnet-api**
* Technology: **system.net**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is suggesting a addition to the original documentation

best

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2290](https://github.com/dotnet/dotnet-api-docs/issues/2290) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @taoyouh 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2290

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
